// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibonzwxlqhrzatmxfion.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlib256d3hscWhyemF0bXhmaW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDYxNzEsImV4cCI6MjA2NTQ4MjE3MX0.G_kDAGe0TiAHzI3VOqwrPdnTacrNYiA8nHoAQFsPOWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);